# This is a config for E2B sandbox template.
# You can use template ID (hgggu04t2bp3hyy3wktz) or template name (chatbot-ui-nextjs-preview) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("chatbot-ui-nextjs-preview") # Sync sandbox
# sandbox = await AsyncSandbox.create("chatbot-ui-nextjs-preview") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('chatbot-ui-nextjs-preview')

template_id = "hgggu04t2bp3hyy3wktz"
dockerfile = "e2b.Dockerfile"
template_name = "chatbot-ui-nextjs-preview"
start_cmd = "/compile_page.sh"
cpu_count = 4
memory_mb = 4_096
team_id = "80020545-1089-4bf1-b7c2-12ce8b8ea06d"
